# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site Settings
title: Rumeysa Yılmaz
title_seperator: "-"
subtitle: "Journey of a Design Engineer"
name: "Rumeysa Yılmaz"
description:
  "A Design Engineer's learning journey penned to encourage,
  inspire and share knowledge attained from various disciplines and people"
url: "https://rumeysayilmaz.github.io"
baseurl: "" # the subpath of your site, e.g. /blog
logo: "/assets/images/apple-touch-icon.png"
words_per_minute: 200
search: true

# Build settings
markdown: kramdown
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: dark
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-polyglot
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist

# jekyll-polyglot settings
languages: ["en", "tr"]
default_lang: "en"
exclude_from_localization: 
  - "assets/css"
  - "assets/images"
  - "assets/js"
  - "assets/res"
parallel_localization: true
sass:
  sourcemap: never

# jekyll-paginate-v2
pagination:
  enabled: true
  per_page: 10
  title: ":title"
  permalink: "/page:num.html"
  sort_reverse: true


# Collections
collections:
  engineering:
    output: true
    permalink: /:collection/:path/
  hobbiescrafts:
    output: true
    permalink: /:collection/:path/
  healthwellbeing:
    output: true
    permalink: /:collection/:path/



defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Site Author
author:
  name   : "Rumeysa Yılmaz"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Design Engineer wearing __interdisiciplinary__ hats"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://rumeysayilmaz.github.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/er_ylmaz"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rumeysayilmaz"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/rumeysa_yilmaz"

# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:ee.design.engineer101@gmail.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/er_ylmaz"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rumeysayilmaz"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/rumeysa_yilmaz"

category_archive:
  type: "liquid"
  path: "/categories/"
tag_archive:
  type: "liquid"
  path: "/tags/"



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
